<?php
/**
 * 用户的一些配置信息
 */
return [
  //默认的网盘容量在oss配置文件中
    'basis_limit'=>[
        [
            'type'=>'oss',
            'type_number'=>2*1024*1024,
        ],
        [
          'type'=>'sms',
          'type_number'=>200,
        ],
        [
            'type'=>'voice',
            'type_number'=>200,
        ],
        [
            'type'=>'e-mail',
            'type_number'=>200,
        ],
        [
            'type'=>'external_company',
            'type_number'=>100,
        ],
    ]
];
